I = imread('cameraMan.jpg');
I=rgb2gray(I);
J = edge(I);
figure;
imshow(I); 
firstDev = edge(J, 'prewitt');
figure;
imshow(firstDev);
secondDev = edge(J, 'log');
figure;
imshow(secondDev); 
cannyAlg = edge(J, 'canny');
figure;
imshow(cannyAlg);